### ISSUE TITLE
test cases using () deprecated

### ISSUE THREAD

**Issue by leslie-alldridge** [realpython/discover-flask#11]
For example,  self.assertTrue(current_user.is_active()) is used throughout tests. However,  self.assertTrue(current_user.is_active) is the correct statement. 

Link for reference: https://stackoverflow.com/questions/32750526/flask-login-raises-typeerror-bool-object-is-not-callable-when-trying-to-overr

Thanks

**Comment by RgnDunes** [comment]
I would love resolving this issue if you allow ?

**Comment by leslie-alldridge** [comment]
@RgnDunes sorry? not sure what you  mean

**Comment by RgnDunes** [comment]
Sorry commented in the wrong issue.
