### ISSUE TITLE
there is no register and email authentication function?

### ISSUE THREAD

**Issue by IamMegatron2025** [realpython/discover-flask#6]
hello, I visit [url](https://www.youtube.com/watch?v=rJGMOOSnHL0&feature=youtu.be) and find there is only login function. So is there no register and email authentication function?

**Comment by mjhea0** [comment]
Both the [Real Python](https://realpython.com) courses as well as the blog post [Handling Email Confirmation During Registration in Flask](https://realpython.com/blog/python/handling-email-confirmation-in-flask/) show how to do this. Hope that helps.

**Comment by IamMegatron2025** [comment]
@mjhea0 thank you very much~
